# Generated by Django 5.0.1 on 2024-04-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentitem",
            name="code",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="paymentitem",
            name="month",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="paymentitem",
            name="number",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="paymentitem",
            name="year",
            field=models.IntegerField(),
        ),
    ]
