# Generated by Django 5.0.1 on 2024-03-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
