# Generated by Django 5.0.1 on 2024-03-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_order_orderproduct_order_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="min_amount_for_free",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
