# Generated by Django 5.0.1 on 2024-03-20 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_alter_order_user"),
        ("profile_user", "0003_alter_profile_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.AddField(
            model_name="order",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="profile_user.profile",
            ),
        ),
    ]
