# Generated by Django 5.0.1 on 2024-03-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0009_order_email_order_fullname_order_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
