# Generated by Django 5.0.1 on 2024-03-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0002_alter_category_subcategories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="subcategories",
            field=models.ManyToManyField(blank=True, to="catalogs.category"),
        ),
    ]
