# Generated by Django 5.0.1 on 2024-03-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0005_productimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "products",
                    models.ManyToManyField(related_name="tags", to="catalogs.product"),
                ),
            ],
        ),
    ]
