# Generated by Django 5.0.1 on 2024-03-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0006_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("value", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "product",
                    models.ManyToManyField(
                        related_name="specifications", to="catalogs.product"
                    ),
                ),
            ],
        ),
    ]
