# Generated by Django 5.0.1 on 2024-03-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0008_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specification",
            name="product",
            field=models.ManyToManyField(
                blank=True, related_name="specifications", to="catalogs.product"
            ),
        ),
    ]
