# Generated by Django 5.0.1 on 2024-03-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0009_alter_specification_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="products",
            field=models.ManyToManyField(
                blank=True, related_name="tags", to="catalogs.product"
            ),
        ),
    ]
