# Generated by Django 5.0.1 on 2024-03-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0010_alter_tag_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2),
        ),
    ]
