# Generated by Django 5.0.1 on 2024-03-09 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0012_review_profile"),
        ("profile_user", "0003_alter_profile_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="reviews",
                to="profile_user.profile",
            ),
        ),
    ]
