# Generated by Django 5.0.1 on 2024-03-11 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0013_alter_review_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="subcategories",
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="subcategories",
                to="catalogs.category",
            ),
        ),
    ]
