# Generated by Django 5.0.1 on 2024-03-12 10:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0014_remove_category_subcategories_category_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salePrice",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10),
                ),
                (
                    "dateFrom",
                    models.DateField(
                        default=datetime.datetime(2024, 3, 12, 13, 29, 5, 708781)
                    ),
                ),
                (
                    "dateTo",
                    models.DateField(
                        default=datetime.datetime(2024, 3, 12, 13, 29, 5, 708781)
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale",
                        to="catalogs.product",
                    ),
                ),
            ],
        ),
    ]
