# Generated by Django 5.0.1 on 2024-03-26 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0033_alter_product_rating_alter_sale_datefrom_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="dateFrom",
            field=models.DateField(
                default=datetime.datetime(2024, 3, 26, 15, 0, 8, 278385)
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="dateTo",
            field=models.DateField(
                default=datetime.datetime(2024, 3, 26, 15, 0, 8, 278385)
            ),
        ),
    ]
