# Generated by Django 5.0.1 on 2024-04-03 11:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0038_alter_sale_datefrom_alter_sale_dateto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product",
                to="catalogs.category",
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="dateFrom",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="sale",
            name="dateTo",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
