# Generated by Django 5.0.1 on 2024-03-26 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0002_alter_basket_session_key_alter_basket_user"),
        ("catalogs", "0035_alter_sale_datefrom_alter_sale_dateto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basketproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogs.product",
                unique=True,
            ),
        ),
    ]
