# Generated by Django 5.0.1 on 2024-03-26 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0003_alter_basketproduct_product"),
        ("catalogs", "0036_alter_sale_datefrom_alter_sale_dateto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basketproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalogs.product"
            ),
        ),
    ]
