# Generated by Django 5.0.1 on 2024-03-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
